---
title: '&#39;Ukončete zkuste&#39; může vyskytovat pouze uvnitř &#39;zkuste&#39; – příkaz'
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: a33f5750a0ba8f833e623101467327635bf0c8d8
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 05/04/2018
---
# <a name="39exit-try39-can-only-appear-inside-a-39try39-statement"></a>&#39;Ukončete zkuste&#39; může vyskytovat pouze uvnitř &#39;zkuste&#39; – příkaz
`Exit Try` lze použít pouze v rámci `Try` blokovat příkaz. Máte buď redundantní `Exit Try` prohlášení, nebo vaše `Exit Try` příkaz zobrazí mimo hranice jeho odpovídající `Try` bloku.  
  
 **ID chyby:** BC30393  
  
## <a name="to-correct-this-error"></a>Oprava této chyby  
  
1.  Vyhledejte a odeberte nadbytečné `Exit Try` příkaz.  
  
2.  Přesunout `Exit Try` příkaz na příslušné místo vašeho kódu.  
  
## <a name="see-also"></a>Viz také  
 [Příkaz Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
