---
title: '&#39;Catch –&#39; nesmí nacházet za &#39;nakonec&#39; v rámci &#39;zkuste&#39; – příkaz'
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: f0eec8db52d71fb61a85a2811f4904c4ad745b67
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 05/04/2018
ms.locfileid: "33611447"
---
# <a name="39catch39-cannot-appear-after-39finally39-within-a-39try39-statement"></a>&#39;Catch –&#39; nesmí nacházet za &#39;nakonec&#39; v rámci &#39;zkuste&#39; – příkaz
A `Catch` příkazu se zobrazí v kódu po `Finally` ukončení `Try` příkaz bloku. `Catch` musí být v rámci `Try...Catch...Finally` příkaz bloku.  
  
 **ID chyby:** BC30379  
  
## <a name="to-correct-this-error"></a>Oprava této chyby  
  
1.  Přesunout `Catch` příkaz na vhodnější místo v kódu.  
  
## <a name="see-also"></a>Viz také  
 [Příkaz Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
