---
title: '&#39;GoTo &lt;název_jmenovky&gt; &#39; není platný protože &#39; &lt;název_jmenovky&gt; &#39; je uvnitř &#39;zkuste&#39;, &#39;Catch&#39; nebo &#39;nakonec&#39; příkaz, který tento příkaz neobsahuje'
ms.date: 07/20/2015
f1_keywords:
- bc30754
- vbc30754
helpviewer_keywords:
- BC30754
ms.assetid: 2eefc7fb-fdf0-41e9-bf60-c3bc93580e14
ms.openlocfilehash: 5cb0af22e94a35643676bb71be2a52c19628d483
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: cs-CZ
ms.lasthandoff: 05/04/2018
ms.locfileid: "33611085"
---
# <a name="39goto-ltlabelnamegt39-is-not-valid-because-39ltlabelnamegt39-is-inside-a-39try39-39catch39-or-39finally39-statement-that-does-not-contain-this-statement"></a>&#39;GoTo &lt;název_jmenovky&gt; &#39; není platný protože &#39; &lt;název_jmenovky&gt; &#39; je uvnitř &#39;zkuste&#39;, &#39;Catch&#39; nebo &#39;nakonec&#39; příkaz, který tento příkaz neobsahuje
Můžete nemůže provést větvení do `Try...Catch...Finally` bloku.  
  
 **ID chyby:** BC30754  
  
## <a name="to-correct-this-error"></a>Oprava této chyby  
  
-   Změny struktury kódu tak, aby předchází popisek `Try...Catch...Finally` bloku.  
  
## <a name="see-also"></a>Viz také  
 [Příkaz Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
